version: '3.1'

services:
  backend:
    image: 'postgres'
    container_name: 'eduverse'
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_USERNAME=arman
      - SPRING_DATASOURCE_PASSWORD=arman08
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - 8088:8080

  pgdb:
    image: 'postgres'
    container_name: 'pg-container'
    environment:
      - POSTGRES_USER=arman
      - POSTGRES_PASSWORD=arman08
      - POSTGRES_DB=learning
    ports:
      - 2345:5432